const {chromium} = require('C:/Users/andyl/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('fs');
const path = require('path');
const assert = require('assert');

(async () => {
  const browser = await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe', headless:true, args:['--enable-unsafe-swiftshader']});
  const page = await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8765/viewer.html');
  await page.waitForFunction(()=>document.getElementById('status').textContent.includes('editable objects loaded'),{timeout:60000});
  const initial=await page.evaluate(()=>window.bakeryViewer.getConfig());
  const transform=id=>page.evaluate(id=>window.bakeryViewer.getTransform(id),id);
  const change=async(id,value)=>{await page.locator('#'+id).fill(String(value));await page.locator('#'+id).press('Tab');};
  await page.locator('#objectSelect').selectOption('coffee_table');
  await change('heightInput',.9);
  assert(Math.abs((await transform('nova2')).position[1]-.9)<1e-5,'support height did not move robot');
  await page.locator('#objectSelect').selectOption('cup_dispenser');
  await change('diameterInput',.12);
  assert(Math.abs((await transform('cup_dispenser')).scale[0]-1.2)<1e-5,'cylinder diameter preview');
  await page.locator('#windowsToggle').uncheck();
  assert.strictEqual((await transform('front_window_left')).visible,false);
  const downloaded=page.waitForEvent('download');
  await page.locator('#downloadButton').click();
  const download=await downloaded;
  const output=path.join(__dirname,'output','viewer-roundtrip.json');
  await download.saveAs(output);
  const saved=JSON.parse(fs.readFileSync(output,'utf8'));
  assert.strictEqual(saved.objects.find(o=>o.id==='coffee_table').height,.9);
  assert.strictEqual(saved.objects.find(o=>o.id==='cup_dispenser').diameter,.12);
  const imported=structuredClone(initial);
  imported.objects.find(o=>o.id==='order_counter').x+=.15;
  await page.locator('#fileInput').setInputFiles({name:'scene_config.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});
  await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Imported'));
  assert(Math.abs((await transform('order_counter')).position[0]-imported.objects.find(o=>o.id==='order_counter').x)<1e-5,'JSON import must change loaded transforms');
  await page.locator('#resetButton').click();
  assert(Math.abs((await transform('nova2')).position[1]-.8)<1e-5,'reset support height');
  await page.locator('#objectSelect').selectOption('nova5');
  await page.screenshot({path:path.join(__dirname,'output','viewer.png')});
  assert.deepStrictEqual(errors,[],'browser page errors');
  console.log(JSON.stringify({passed:true,editable_objects:initial.objects.length,checks:['GLB load','support heights','dispenser diameter','window visibility','JSON export','JSON import','reset'],page_errors:errors}));
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
