const {chromium}=require('C:/Users/andyl/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
 try{
  const page=await browser.newPage({viewport:{width:1700,height:1100}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8766/viewer.html?workflow=coffee');
  await page.waitForFunction(()=>window.coffeeEditor?.ready&&coffeeEditor.coffee.result?.pathOK,null,{timeout:90000});
  const report=await page.evaluate(async()=>{
   const T=await import('./vendor/three.module.js'),C=await import('./editor/collision-core.js'),S=await import('./editor/collision-scene.js');
   const M=await import('./editor/motion-search.js'),{SuctionArm}=await import('./editor/ik-core.js');
   const {makeCoffeeRequest}=await import('./editor/coffee-geometry.js'),{solveCoffeeFlow}=await import('./editor/coffee-solver.js');
   const {makeWorkflowRequest}=await import('./editor/flow-geometry.js'),{checkBreadWorkflow}=await import('./editor/bread-flow.js');
   const {rackBreads,BREAD_DEFAULTS}=await import('./editor/bread-geometry.js'),{rotate}=await import('./editor/store.js');
   const e=coffeeEditor,checks=[];
   const check=(ok,message)=>{if(!ok)throw new Error(message);checks.push(message);};
   const near=(a,b,tol=1e-7)=>Math.abs(a-b)<tol;
   const unit=C.makeBox([0,0,0],[.05,.05,.05]);
   check(C.boxesOverlap(unit,C.makeBox([.098,0,0],[.05,.05,.05])),'Zero clearance rejects 2 mm overlap');
   check(!C.boxesOverlap(unit,C.makeBox([.098,0,0],[.05,.05,.05]),-.003),'Negative 3 mm clearance accepts 2 mm overlap');
   check(C.boxesOverlap(unit,C.makeBox([.095,0,0],[.05,.05,.05]),-.003),'Negative 3 mm clearance still rejects 5 mm overlap');
   check(C.boxesOverlap(unit,C.makeBox([.102,0,0],[.05,.05,.05]),.003),'Positive 3 mm clearance requires a gap');
   e.store.scene.collision_settings={enabled:true,margin:-.002,search:true,searchNodes:600};
   const definition=e.coffee.definition,robot=e.coffee.request.robot,arm=new SuctionArm(definition,robot,e.store.z(robot));
   const data=S.collisionRequest(e.three,robot);data.world=[];
   arm.collision=new C.WorldCollisionChecker(data);
   const q0=[-.8,-.7,-1.4,0,1.5,0],q1=[.8,-.7,-1.4,0,1.5,0];
   const middle=q0.map((v,i)=>(v+q1[i])/2),shape=arm.collision.shapes(middle).find(s=>s.link==='Link3');
   data.world.push(C.makeBox(shape.center,[.025,.025,.025],undefined,{objectId:'test',label:'Test obstacle',part:'Block'}));
   const from={q:q0,time:0,phase:'Start'},to={q:q1,time:2,phase:'Move clear test obstacle'};
   check(!arm.collision.pose(q0)&&!arm.collision.pose(q1),'Detour endpoints are collision-free');
   check(!!arm.collision.interval(from,to),'Original straight joint route collides');
   const plan=M.searchJointPath(arm,from,to);
   check(plan.ok&&plan.nodes>0&&plan.path.length>2,'RRT finds a genuine detour around the world obstacle');
   check(plan.path.slice(1).every((q,i)=>!arm.collision.interval({...from,q:plan.path[i]},{...to,q})),'Every returned detour edge passes the swept collision check');
   const frames=M.detourFrames(arm,from,to,plan.path);
   check(frames.frames.slice(1).every((f,i)=>f.time>frames.frames[i].time),'Detour frame times are strictly increasing');
   const exhausted=M.searchJointPath(arm,from,to,{budget:{remaining:0}});
   check(exhausted.status==='budget_exhausted'&&!exhausted.ok,'Search exhaustion explicitly reported');
   data.search=false;check(M.searchJointPath(arm,from,to).status==='search_disabled','Detour search can be disabled');data.search=true;
   data.world.push(C.makeBox(arm.collision.shapes(q0).find(s=>s.link==='Link3').center,[.1,.1,.1],undefined,{objectId:'start-block'}));
   check(M.searchJointPath(arm,from,to).status==='start_in_collision','Overlapping start gets a distinct failure reason');data.world.pop();
   data.world.push(C.makeBox(arm.collision.shapes(q1).find(s=>s.link==='Link3').center,[.1,.1,.1],undefined,{objectId:'end-block'}));
   check(M.searchJointPath(arm,from,to).status==='goal_in_collision','Overlapping goal gets a distinct failure reason');data.world.pop();
   const pose=q=>{const f=arm.forward(q);return {position:f.position.toArray(),quaternion:f.quaternion.toArray()};};
   const base=makeCoffeeRequest(e.store,definition);
   const testRequest={...base,robot:{...robot,joints_deg:Object.fromEntries(definition.joints.map((j,i)=>[j.name,q0[i]*180/Math.PI]))},
    knots:[{...pose(q0),time:0,phase:'Start',cup:'none',grip:0},{...pose(q1),time:2,phase:'Move clear test obstacle',cup:'none',grip:0}],
    events:[{time:2,phase:'Move clear test obstacle',signal:'test'}],duration:2,collision:data,collisionRoutes:[]};
   const integrated=solveCoffeeFlow(definition,testRequest);
   check(integrated.pathOK&&integrated.searches.some(s=>s.ok),'Coffee planner inserts a searched detour into its real playback frames: '+JSON.stringify(integrated.failure));
   check(integrated.frames.some(f=>f.moveType==='searched detour'),'Searched frames are retained for playback');
   check(integrated.duration>2&&integrated.speed.boundAfter<=1.5+1e-6,'Detours lengthen timing and retain the 1.5 m/s end-effector limit');
   check(integrated.route.events[0].time===integrated.route.knots.at(-1).time,'Coffee event times follow the longer route');
   const retimed=M.retimeDetours({frames:[from,to],searches:[{ok:true,startTime:0,endTime:2,suggestedDuration:4}],
    failure:{time:3,previous:{time:2},segment:{startTime:2,endTime:3}}},[{time:0},{time:2},{time:3}],[{time:3}]);
   check(retimed.result.failure.time===5&&retimed.result.failure.segment.startTime===4&&retimed.events[0].time===5,'Later failure and event diagnostics retain the correct retimed timestamps');
   const {inspectHeldInterval}=await import('./editor/bag-motion.js');
   const heldRequest=S.attachCollisions(e.three,structuredClone(e.coffee.request));
   const heldMid=e.coffee.result.frames.find(f=>f.cup==='held'&&f.collisionCup==='held');
   const heldStart={...heldMid,q:heldMid.q.map((v,i)=>i===0?v-.8:v),time:0,collisionCup:'held'};
   const heldEnd={...heldMid,q:heldMid.q.map((v,i)=>i===0?v+.8:v),time:3,collisionCup:'held'};
   const heldArm=new SuctionArm(definition,robot,e.store.z(robot));
   heldRequest.collision.world=[];
   heldArm.collision=new C.WorldCollisionChecker(heldRequest.collision);
   const cupShape=heldArm.collision.shapes(heldMid.q,0,heldMid).find(s=>s.payload);
   heldRequest.collision.world.push(C.makeBox(cupShape.center,[.016,.016,.016],undefined,{objectId:'cup-block',label:'Cup path blocker',part:'Solid'}));
   check(!heldArm.collision.pose(heldStart.q,0,heldStart)&&!heldArm.collision.pose(heldEnd.q,0,heldEnd)&&!!heldArm.collision.interval(heldStart,heldEnd),'Held-cup test has clear endpoints and a blocked direct sweep');
   const heldPlan=M.searchJointPath(heldArm,heldStart,heldEnd,{tiltLimit:3});
   check(heldPlan.ok&&heldPlan.nodes>0,'Obstacle search finds a route while holding the cup');
   check(heldPlan.path.slice(1).every((q,i)=>!heldArm.collision.interval({...heldStart,q:heldPlan.path[i]},{...heldEnd,q})&&inspectHeldInterval(heldArm,{...heldStart,q:heldPlan.path[i]},{...heldEnd,q},3).ok),'Held cup remains attached, collision-free and within its upright tilt bound throughout the detour');
   const breadDef=await fetch('./robot-library/nova5_bread-kinematics.json').then(r=>r.json());
   const wide=makeWorkflowRequest(e.store,{bread_mode:'nova'}).breadTask;
   const rejected=checkBreadWorkflow(breadDef,wide);
   check(!rejected.pathOK&&rejected.errors[0].includes('bun width'),'Actual jaw aperture rejects a too-wide side grip with a clear explanation');
   for(const shelf of e.store.scene.objects.filter(o=>o.kind==='shelf'))shelf.shelf_overrides={...e.store.shelfSettings(shelf),bread_length_1:.06};
   e.three.sync();
   const bread=makeWorkflowRequest(e.store,{bread_mode:'nova'}).breadTask,solved=checkBreadWorkflow(breadDef,bread);
   check(solved.pathOK,'Real-size tongs can plan a side grip for a 6 cm bun');
   const candidate=solved.candidate,tool=new T.Quaternion(...candidate.toolQuaternion),bunQ=new T.Quaternion(...candidate.quaternion);
   const close=new T.Vector3(1,0,0).applyQuaternion(tool),width=new T.Vector3(1,0,0).applyQuaternion(bunQ);
   check(Math.abs(close.dot(width))>.99,'Jaw closing axis spans the sides of the bun');
   const plusZ=new T.Vector3(0,0,1).applyQuaternion(tool),advance=new T.Vector3(...candidate.position).sub(new T.Vector3(...candidate.prePosition)).normalize();
   check(plusZ.dot(advance)>.99999,'Configured pre-pick aims tool +Z directly at the selected bun');
   const relative=new T.Quaternion(...candidate.relative);
   check(tool.clone().multiply(relative).angleTo(bunQ)<1e-7,'Bread keeps its rack orientation when attached to the side-grip tool');
   check(new T.Quaternion(...candidate.releaseQuaternion).multiply(relative).angleTo(new T.Quaternion(...bread.heldQuaternion))<1e-7,'Release pose puts the bun on its edge into the bag');
   const shelf=e.store.object(bread.shelfId),savedYaw=shelf.yaw_deg;
   shelf.yaw_deg=37;
   const fixed={...BREAD_DEFAULTS,bread_pre_pick_mode:'fixed',bread_pre_pick_x:-.12,bread_pre_pick_y:-.35,bread_pre_pick_z:.8};
   const targets=rackBreads(e.store,shelf,bread.robot,fixed),xy=rotate(-.12,-.35,37),expected=[shelf.x+xy[0],shelf.y+xy[1],e.store.z(shelf)+.8];
   check(targets.length>0&&targets.every(c=>c.prePosition.every((v,i)=>near(v,expected[i]))),'Fixed signed pre-pick coordinates rotate and translate with the rack');
   shelf.yaw_deg=savedYaw;
   e.store.scene.collision_settings.enabled=false;
   e.store.scene.bag_workflow={...e.store.scene.bag_workflow,bread_mode:'nova',auto_check:false};
   e.three.sync();
   return {checks,detour:{nodes:plan.nodes,waypoints:plan.path.length,duration:integrated.duration,searches:integrated.searches,heldNodes:heldPlan.nodes},bread:{candidate:solved.candidate,pre:bread.candidates[0].prePosition},widthMessage:rejected.errors[0]};
  });
  console.log(JSON.stringify(report,null,2));
  await page.locator('#collision-menu summary').click();
  await page.locator('#collision-margin').fill('-.3');await page.locator('#collision-margin').press('Tab');
  await page.locator('#collision-nodes').fill('900');await page.locator('#collision-nodes').press('Tab');
  await page.locator('#collision-search').uncheck();
  const policy=await page.evaluate(()=>coffeeEditor.store.exportScene().collision_settings);
  assert.equal(policy.margin,-.003);assert.equal(policy.searchNodes,900);assert.equal(policy.search,false);
  await page.locator('#collision-menu summary').click();
  await page.locator('[data-workflow="bag"]').click();
  await page.locator('[data-flow-setting="bread_pre_pick_mode"]').selectOption('fixed');
  await page.locator('[data-flow-setting="bread_pre_pick_x"]').fill('-12');
  await page.locator('[data-flow-setting="bread_pre_pick_x"]').press('Tab');
  assert.equal(await page.evaluate(()=>coffeeEditor.flow.settings().bread_pre_pick_x),-.12);
  await page.locator('[data-flow-setting="bread_pre_pick_mode"]').selectOption('offset');
  await page.locator('[data-flow-setting="bread_pre_pick_x"]').fill('0');
  await page.locator('[data-flow-setting="bread_pre_pick_x"]').press('Tab');
  await page.locator('[data-bread-action="preview"]:visible').click();
  await page.waitForFunction(()=>coffeeEditor.three.breadPrePickGuide?.children.length===3);
  const preview=await page.evaluate(async()=>{
   const T=await import('./vendor/three.module.js'),{makeWorkflowRequest}=await import('./editor/flow-geometry.js');
   const e=coffeeEditor,record=e.three.instances.get('nova5'),bread=makeWorkflowRequest(e.store).breadTask;
   const desired=e.three.breadPrePickGuide.userData.candidate.prePosition,p=record.tcp.getWorldPosition(new T.Vector3());
   return {position:p.toArray(),error:p.distanceTo(new T.Vector3(desired[0],desired[2],-desired[1]))};
  });
  assert.ok(preview.error<.002,JSON.stringify(preview));
  await page.screenshot({path:path.join(__dirname,'output/bread-pre-pick-controls.png')});
  await page.locator('[data-bread-action="capture"]:visible').click();
  await page.waitForFunction(()=>coffeeEditor.flow.settings().bread_pre_pick_mode==='fixed');
  const captured=await page.evaluate(()=>coffeeEditor.flow.settings());
  assert.ok(Number.isFinite(captured.bread_pre_pick_y));
  await page.waitForTimeout(500);await page.reload();
  await page.waitForFunction(()=>window.coffeeEditor?.ready);
  const saved=await page.evaluate(()=>({policy:coffeeEditor.store.scene.collision_settings,settings:coffeeEditor.flow.settings()}));
  assert.equal(saved.policy.margin,-.003);assert.equal(saved.policy.searchNodes,900);assert.equal(saved.policy.search,false);
  assert.equal(saved.settings.bread_pre_pick_mode,'fixed');
  assert.deepEqual(errors,[]);
  fs.writeFileSync(path.join(__dirname,'output/motion-search-test-report.json'),JSON.stringify({...report,policy,preview,saved,errors},null,2));
  console.log('UI controls, negative clearance, rack-relative pre-pick capture and persistence passed.');
 }finally{await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
