const {chromium} = require('C:/Users/andyl/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
  try {
    const page = await browser.newPage({viewport:{width:1750,height:1150},acceptDownloads:true});
    const errors = [];
    page.on('pageerror', error => errors.push(error.stack));
    await page.goto('http://127.0.0.1:8766/viewer.html',{waitUntil:'networkidle'});
    await page.waitForFunction(() => window.coffeeEditor?.ready, {timeout:45000});
    const facts = await page.evaluate(async () => {
      const {store,three} = coffeeEditor;
      const params = await import('./editor/barrier-parameters.js');
      const THREE = await import('./vendor/three.module.js');
      window.barrierTest = {params,THREE};
      const object=store.object('customer_barrier');
      store.select(object.id);
      const record=three.instances.get(object.id);
      const p=params.barrierSettings(object);
      const opening=params.pickupWorld(object,store.z(object));
      const ray = new THREE.Raycaster(new THREE.Vector3(opening.center[0]+.1,opening.center[2],-opening.center[1]),new THREE.Vector3(-1,0,0),0,.2);
      const hits=ray.intersectObject(record.mesh,true).map(hit=>hit.object.name);
      ray.set(new THREE.Vector3(opening.center[0]+.1,store.z(object)+.7,-opening.center[1]),new THREE.Vector3(-1,0,0));
      const plasticHits=ray.intersectObject(record.mesh,true).map(hit=>hit.object.userData.barrierRole);
      return {object,p,opening,hits,plasticHits,top:new THREE.Box3().setFromObject(record.node).max.y,warnings:params.barrierWarnings(object),panels:record.mesh.children.map(node=>node.userData.barrierPanel)};
    });
    assert.deepEqual(facts.hits,[]);
    assert.ok(Math.abs(facts.top-1.7)<1e-6);
    assert.ok(facts.plasticHits.includes('plastic'));
    assert.deepEqual(facts.panels,['front','right']);
    assert.deepEqual(facts.warnings,[]);
    assert.equal(facts.object.support,'coffee_station');
    assert.equal(await page.locator('[data-barrier-panel]').count(),2);
    await page.locator('[data-field="barrier_pickup_width"]').fill('38');
    await page.locator('[data-field="barrier_pickup_width"]').press('Tab');
    assert.equal(await page.evaluate(()=>coffeeEditor.store.object('customer_barrier').barrier.pickup_width),.38);
    const actualOpening=await page.evaluate(()=>{let opening;coffeeEditor.three.instances.get('customer_barrier').mesh.traverse(n=>{if(n.userData.barrierRole==='pickup-opening')opening=n.userData;});return opening;});
    assert.equal(actualOpening.clearWidth,.38);
    for (const [key,value] of [['pickup_height','35'],['pickup_bottom','8'],['pickup_center','20']]) {
      const field=page.locator('[data-field="barrier_'+key+'"]');await field.fill(value);await field.press('Tab');
    }
    const adjusted=await page.evaluate(()=>{
      const {params,THREE}=barrierTest,{store,three}=coffeeEditor;
      const object=store.object('customer_barrier'),point=params.pickupWorld(object,store.z(object));
      const ray=new THREE.Raycaster(new THREE.Vector3(point.center[0]+.1,point.center[2],-point.center[1]),new THREE.Vector3(-1,0,0),0,.2);
      const hits=ray.intersectObject(three.instances.get(object.id).mesh,true);
      return {point,hits:hits.length};
    });
    assert.equal(adjusted.hits,0);assert.equal(adjusted.point.height,.35);
    assert.ok(Math.abs(adjusted.point.center[2]-1.155)<1e-8);
    assert.ok(Math.abs(adjusted.point.center[1]-1.65)<1e-8);
    await page.locator('#align-barrier-opening').click();
    await page.locator('#units').selectOption('px');
    assert.equal(await page.locator('[data-field="barrier_pickup_width"]').inputValue(),'76');
    await page.locator('#units').selectOption('cm');
    await page.waitForFunction(()=>document.querySelector('#save-status').textContent.startsWith('Saved locally'));
    await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>coffeeEditor.ready);
    assert.equal(await page.evaluate(()=>coffeeEditor.store.object('customer_barrier').barrier.pickup_width),.38);
    await page.locator('[data-barrier="pickup_side"]').selectOption('front');
    await page.locator('[data-barrier="right_return"]').uncheck();
    assert.equal(await page.locator('[data-barrier-panel]').count(),1);
    assert.equal(await page.evaluate(()=>coffeeEditor.three.instances.get('customer_barrier').mesh.children.length),1);
    await page.evaluate(()=>coffeeEditor.store.reset());
    await page.evaluate(()=>coffeeEditor.store.select('customer_barrier'));
    await page.locator('#delete').click();
    await page.locator('[data-panel="library"]').click();await page.locator('[data-add-barrier]').click();
    assert.equal(await page.evaluate(()=>coffeeEditor.store.scene.objects.filter(o=>o.kind==='customer_barrier').length),1);
    await page.evaluate(()=>coffeeEditor.store.reset());
    const lifecycle=await page.evaluate(async()=>{
      const {store,three,plan}=coffeeEditor;
      const original=store.exportScene();
      const legacy=structuredClone(original);legacy.editor_revision=6;
      legacy.objects=legacy.objects.filter(o=>o.kind!=='customer_barrier');
      legacy.objects.find(o=>o.id==='milk_fridge').yaw_deg=37;
      store.importScene(legacy);
      const migrated={count:store.scene.objects.filter(o=>o.kind==='customer_barrier').length,rotation:store.object('milk_fridge').yaw_deg,revision:store.scene.editor_revision};
      store.select('customer_barrier');
      const {captureComponents,insertComponents}=await import('./editor/component-copy.js');
      const copied=captureComponents(store);
      insertComponents(store,copied);
      const copy=store.object(store.selected[0]);
      const copyFacts={kind:copy.kind,settings:copy.barrier,instance:three.instances.has(copy.id)};
      store.removeSelected();store.undo();const undo=three.instances.has(copy.id);
      store.importScene(original);store.select('customer_barrier');store.removeSelected();
      const deleted=store.exportScene();store.importScene(deleted);
      const notReadded=!store.scene.objects.some(o=>o.kind==='customer_barrier');
      store.importScene(original);
      store.transact('Test support change',()=>store.patch('coffee_station',{x:1,y:1.8,yaw_deg:30,height:1.0}));
      const moved=store.object('customer_barrier'),node=three.instances.get(moved.id).node;
      const support={x:moved.x,y:moved.y,yaw:moved.yaw_deg,z:node.position.y};
      store.toggleVisibility('coffee_station');const hidden=!node.visible;store.toggleVisibility('coffee_station');
      store.importScene(original);
      const svg=await plan.exportSVG(false);await coffeeEditor.importText(svg,'scene.svg');
      const reimported=store.scene.objects.some(o=>o.kind==='customer_barrier');
      return {migrated,copyFacts,undo,notReadded,support,hidden,reimported,svgHasSections:svg.includes('data-barrier-section="pickup"')};
    });
    assert.equal(lifecycle.migrated.count,1);
    assert.equal(lifecycle.migrated.rotation,37);
    assert.equal(lifecycle.migrated.revision,7);
    assert.equal(lifecycle.copyFacts.kind,'customer_barrier');
    assert.ok(lifecycle.copyFacts.instance && lifecycle.undo && lifecycle.notReadded && lifecycle.hidden && lifecycle.reimported && lifecycle.svgHasSections);
    assert.equal(lifecycle.support.z,1);
    assert.equal(lifecycle.support.yaw,30);
    await page.waitForFunction(()=>coffeeEditor.flow.result && !coffeeEditor.flow.pending,{timeout:60000});
    assert.deepEqual(await page.evaluate(()=>coffeeEditor.flow.request.errors),[]);
    assert.ok(await page.evaluate(()=>coffeeEditor.flow.result.pathOK));
    const download=page.waitForEvent('download');
    await page.evaluate(()=>coffeeEditor.exportFile('glb'));
    const file=await download;
    await file.saveAs(path.join(__dirname,'output/customer-barrier-export.glb'));
    const glb=fs.readFileSync(path.join(__dirname,'output/customer-barrier-export.glb'));
    const json=JSON.parse(glb.subarray(20,20+glb.readUInt32LE(12)).toString());
    assert.ok(json.nodes.some(n=>n.name==='Pickup clear opening'));
    assert.ok(json.nodes.some(n=>n.name==='Ordering touchscreen'));
    assert.ok(json.images?.length>=2);
    await page.evaluate(()=>{
      const {store,three}=coffeeEditor;store.select('customer_barrier');store.setOption('view','scene');
      three.camera.position.set(3.45,2.35,1.65);three.controls.target.set(.75,1.10,-1.25);three.controls.update();
    });
    await page.waitForTimeout(800);
    await page.screenshot({path:path.join(__dirname,'output/customer-barrier-editor.png')});
    await page.locator('#scene').screenshot({path:path.join(__dirname,'output/customer-barrier-view.png')});
    fs.writeFileSync(path.join(__dirname,'output/customer-barrier-test-report.json'),JSON.stringify({facts,lifecycle,errors,exportNodes:json.nodes.length},null,2));
    assert.deepEqual(errors,[]);
    console.log('PASS: barrier opening raycasts, live controls and units, panel toggles, support transforms, visibility, copy/delete/undo, revision migration, SVG and textured GLB exports.');
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
