const {chromium}=require('C:/Users/andyl/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert/strict'),fs=require('fs'),path=require('path');
(async()=>{
  const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});const page=await browser.newPage({viewport:{width:1660,height:1080}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8766/viewer.html',{waitUntil:'networkidle'});await page.waitForFunction(()=>coffeeEditor.ready);
  const read=()=>page.evaluate(()=>({o:coffeeEditor.store.object('nova5_cart'),n:coffeeEditor.store.object('nova5'),m:coffeeEditor.three.inspect('nova5_cart')}));
  await page.locator('[data-layer="nova5_cart"] .layer-label').click();const initial=await read();
  const handle=page.locator('[data-handle="resize"]').nth(2);let box=await handle.boundingBox();await page.mouse.move(box.x+5,box.y+5);await page.mouse.down();await page.mouse.move(box.x+35,box.y+25,{steps:5});await page.mouse.up();let s=await read();assert.ok(s.o.width>initial.o.width&&s.o.depth>initial.o.depth);assert.ok(Math.abs(s.m.scale[0]-s.o.width/.6)<1e-8);await page.locator('#undo').click();
  const rotation=await page.locator('[data-selection-overlay]').evaluate(el=>{const p=new DOMPoint(0,0).matrixTransform(el.getScreenCTM()),c=el.querySelector('[data-handle="rotate"]'),q=new DOMPoint(+c.getAttribute('cx'),+c.getAttribute('cy')).matrixTransform(c.getScreenCTM());return {centre:{x:p.x,y:p.y},handle:{x:q.x,y:q.y}};});const {centre:c,handle:h}=rotation;
  await page.mouse.move(h.x,h.y);await page.mouse.down();await page.mouse.move(c.x-(h.y-c.y),c.y+(h.x-c.x),{steps:6});await page.mouse.up();s=await read();assert.ok(Math.abs(s.o.yaw_deg+90)<.2);await page.locator('#undo').click();
  // Drag a robot card onto the coffee table and verify it mounts at tabletop height.
  await page.locator('[data-panel="library"]').click();const loc=await page.evaluate(()=>{const p=new DOMPoint(.75*200,(5.75-1.12)*200).matrixTransform(document.querySelector('#plan').getScreenCTM());return {x:p.x,y:p.y};});
  await page.locator('[data-robot="me6"]').dispatchEvent('dragstart',{dataTransfer:await page.evaluateHandle(()=>{const dt=new DataTransfer();dt.setData('application/robot-key','me6');return dt;})});
  await page.locator('#plan').dispatchEvent('drop',{clientX:loc.x,clientY:loc.y,dataTransfer:await page.evaluateHandle(()=>{const dt=new DataTransfer();dt.setData('application/robot-key','me6');return dt;})});
  const robot=await page.evaluate(()=>{const id=coffeeEditor.store.selected[0];return {o:coffeeEditor.store.object(id),m:coffeeEditor.three.inspect(id)};});assert.equal(robot.o.model_key,'me6');assert.equal(robot.o.support,'coffee_station');assert.equal(robot.m.position[1],.9);
  await page.evaluate(()=>coffeeEditor.store.reset());await page.locator('[data-view="scene"]').click();await page.locator('#scene-top').click();await page.locator('#move-mode').click();
  const target=await page.evaluate(async()=>{const {Vector3}=await import('./vendor/three.module.js');const v=coffeeEditor.three,o=coffeeEditor.store.object('middle_counter');v.controls.update();v.camera.updateMatrixWorld();const p=new Vector3(o.x,o.height+.01,-o.y).project(v.camera),r=v.canvas.getBoundingClientRect();const point={clientX:r.left+(p.x+1)/2*r.width,clientY:r.top+(1-p.y)/2*r.height};return {...point,id:v.hit(point),x:o.x,y:o.y,camera:v.camera.position.toArray(),quaternion:v.camera.quaternion.toArray(),target:v.controls.target.toArray(),rect:{x:r.x,y:r.y,width:r.width,height:r.height}};});assert.equal(target.id,'middle_counter');
  await page.mouse.move(target.clientX,target.clientY);await page.mouse.down();await page.mouse.move(target.clientX+40,target.clientY+10,{steps:6});await page.mouse.up();const after=await page.evaluate(()=>({o:coffeeEditor.store.object('middle_counter'),m:coffeeEditor.three.inspect('middle_counter')}));assert.ok(Math.hypot(after.o.x-target.x,after.o.y-target.y)>.02);assert.equal(after.m.position[0],after.o.x);assert.equal(after.m.position[2],-after.o.y);
  const invalid=await page.evaluate(()=>{const data=coffeeEditor.getState();data.objects[0].support=data.objects[0].id;try{coffeeEditor.store.importScene(data);return false;}catch(e){return e.message.includes('cycle');}});assert.equal(invalid,true);
  // A native rebuild fixture with cloned robots, scaling, moved furniture, and deleted human/shelf.
  const config=await page.evaluate(()=>{const e=coffeeEditor;e.store.reset();const id=e.store.addRobot('me6',.8,1.15);e.store.addRobot('mg400',.8,1.7);e.store.transact('Scale robot',()=>e.store.resize(id,.176,.132));e.store.select('human');e.store.removeSelected();e.store.select('shelf_1');e.store.removeSelected();return e.getState();});fs.writeFileSync(path.join(__dirname,'output','editor-rebuild-fixture.json'),JSON.stringify(config,null,2));
  assert.deepEqual(errors,[]);console.log('PASS: SVG resize and rotation handles, tabletop robot drag/drop, 3D dragging, cyclic-import rejection, rebuild fixture.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
