const {chromium}=require('C:/Users/andyl/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert/strict'),fs=require('fs'),path=require('path');
const output=path.join(__dirname,'output');
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
(async()=>{
  const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
  const page=await browser.newPage({viewport:{width:1660,height:1080},deviceScaleFactor:1,acceptDownloads:true}),errors=[],passed=[];
  page.on('pageerror',e=>errors.push(e.stack));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.goto('http://127.0.0.1:8766/viewer.html',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.coffeeEditor?.ready);
  async function state(){return page.evaluate(()=>({scene:coffeeEditor.getState(),selected:coffeeEditor.store.selected,models:[...coffeeEditor.three.instances].map(([id])=>[id,coffeeEditor.three.inspect(id)]),rings:document.querySelectorAll('[data-reach-owner] circle').length,rings3d:coffeeEditor.three.guides.children.filter(n=>n.userData.reachOwner).length,distances:coffeeEditor.store.distances()}));}
  async function select(id){await page.locator(`[data-layer="${id}"] .layer-label`).click();}
  async function field(name,value){const loc=page.locator(`[data-field="${name}"]`);await loc.fill(String(value));await loc.press('Tab');}
  let s=await state();assert.equal(s.scene.objects.length,25);assert.equal(s.models.length,25);assert.equal(s.rings,2);assert.equal(s.rings3d,2);near(s.distances[0].distance,.35);passed.push('All 25 objects load; selected Nova-5 has matching rings and 35 cm shelf distance.');
  const initialCart=s.scene.objects.find(o=>o.id==='middle_counter'),nova=s.scene.objects.find(o=>o.id==='nova5');near(initialCart.width,1.05);near(initialCart.depth,1.8);assert.equal(nova.support,'middle_counter');
  await page.locator('#units').selectOption('px');assert.equal(await page.locator('[data-field="x"]').inputValue(),'370');assert.match(await page.locator('[data-distance-robot="nova5"][data-distance-target="shelf_2"] text').textContent(),/70 px/);await page.locator('#units').selectOption('cm');passed.push('Centimetre/pixel toggle and 2 px/cm scale are correct; both packing robots share the adjustable table.');
  // Use actual mouse dragging in the SVG, then verify the Three.js transform.
  const point=await page.locator('[data-object-id="nova5"]').evaluate(el=>{const p=new DOMPoint(0,0).matrixTransform(el.getScreenCTM());return {x:p.x,y:p.y};});
  await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+32,point.y-20,{steps:5});await page.mouse.up();
  s=await state();let moved=s.scene.objects.find(o=>o.id==='nova5');assert.ok(moved.x>nova.x);near(s.models.find(([id])=>id==='nova5')[1].position[0],moved.x);near(s.models.find(([id])=>id==='nova5')[1].position[2],-moved.y);await page.locator('#undo').click();
  await select('middle_counter');await field('x',191.5);s=await state();near(s.scene.objects.find(o=>o.id==='nova5').x,2.14);near(s.models.find(([id])=>id==='nova5')[1].position[0],2.14);await page.locator('#undo').click();
  await field('rotation',90);s=await state();const rotated=s.scene.objects.find(o=>o.id==='nova5');near(rotated.x,1.225);near(rotated.y,2.825);near(s.models.find(([id])=>id==='nova5')[1].quaternion[1],Math.sin(Math.PI/4));await page.locator('#undo').click();
  await field('height',95);s=await state();near(s.models.find(([id])=>id==='nova5')[1].position[1],.95);await page.locator('#undo').click();
  await field('width',72);s=await state();near(s.models.find(([id])=>id==='middle_counter')[1].scale[0],.72/1.05);await page.locator('#undo').click();passed.push('SVG dragging, numeric resize/rotate and support movement/height update the actual 3D scene; undo restores it.');
  await page.locator('[data-layer="area_coffee"] [data-action="visibility"]').click();s=await state();for(const id of ['coffee_station','nova2','ice_machine','cup_dispenser'])assert.equal(s.models.find(([key])=>key===id)[1].visible,false);await page.locator('#undo').click();
  await select('middle_counter');await page.locator('#delete').click();s=await state();assert.ok(!s.models.some(([id])=>id==='middle_counter'||id==='nova5'));await page.locator('#undo').click();passed.push('Area visibility and deleting a support are synchronized, including its supported equipment.');
  await page.locator('#show-reach').check();await page.locator('#show-distances').check();s=await state();assert.equal(s.rings,8);assert.equal(s.rings3d,8);assert.equal(s.distances.length,14);await page.locator('#distance-mode').selectOption('both');s=await state();assert.equal(s.distances.length,28);await page.locator('#distance-mode').selectOption('center');await page.locator('#show-reach').uncheck();await page.locator('#show-distances').uncheck();
  const geometry=await page.evaluate(async()=>{const {edgeGap,closestPoint}=await import('./editor/store.js');return {gap:edgeGap({x:0,y:0,width:4,depth:.2,yaw_deg:45},{x:0,y:0,width:4,depth:.2,yaw_deg:-45}).distance,point:closestPoint([0,0],{x:1,y:0,width:1,depth:2,yaw_deg:90})};});near(geometry.gap,0);near(geometry.point[0],0);passed.push('All/selected overlays, both distance conventions and rotated-footprint geometry work.');
  await page.locator('[data-panel="library"]').click();
  const newIds=[];for(const key of ['nova2','nova5','me6','mg400','atom_w','nova5_suction']){await page.locator(`[data-robot="${key}"] button`).click();s=await state();newIds.push(s.selected[0]);const o=s.scene.objects.find(o=>o.id===s.selected[0]);assert.equal(o.model_key,key);assert.ok(s.models.some(([id])=>id===o.id));const meshes=await page.evaluate(id=>{let count=0;coffeeEditor.three.instances.get(id).node.traverse(n=>{if(n.isMesh)count++;});return count;},o.id);assert.ok(meshes>3);}
  s=await state();assert.equal(s.scene.objects.length,32);assert.equal(s.models.length,32);passed.push('Every library robot adds actual URDF geometry to 3D; Nova-5 also adds its cart.');
  // Change dimensions and visibility, then round-trip exports, including hidden state.
  await page.locator('[data-panel="layers"]').click();await select('ice_machine');await field('width',47);await page.locator('[data-layer="milk_fridge"] [data-action="visibility"]').click();
  await page.locator('#show-reach').check();await page.locator('#show-distances').check();
  let svg=await page.evaluate(()=>coffeeEditor.plan.exportSVG(true));fs.writeFileSync(path.join(output,'editor-test-export.svg'),svg);
  const exportInfo=await page.evaluate(svg=>{const doc=new DOMParser().parseFromString(svg,'image/svg+xml');return {errors:doc.querySelector('parsererror')?.textContent,objects:doc.querySelectorAll('[data-object-id]').length,package:!!doc.querySelector('#package_nova5 [data-reach-owner="nova5"]'),data:JSON.parse(doc.querySelector('#coffee-scene-data').textContent)};},svg);
  assert.ok(!exportInfo.errors,exportInfo.errors);assert.equal(exportInfo.objects,32);assert.ok(exportInfo.package);assert.equal(exportInfo.data.objects.find(o=>o.id==='milk_fridge').enabled,false);
  await page.evaluate(async svg=>{coffeeEditor.store.reset();await coffeeEditor.importText(svg,'test.svg');},svg);s=await state();assert.equal(s.scene.objects.length,32);near(s.scene.objects.find(o=>o.id==='ice_machine').width,.47);assert.equal(s.models.find(([id])=>id==='milk_fridge')[1].visible,false);
  const dl=page.waitForEvent('download');await page.locator('#export-menu summary').click();await page.locator('[data-export="glb"]').click();const file=await dl;await file.saveAs(path.join(output,'editor-test-export.glb'));const buffer=fs.readFileSync(path.join(output,'editor-test-export.glb'));assert.equal(buffer.toString('utf8',0,4),'glTF');const jsonLength=buffer.readUInt32LE(12),gltf=JSON.parse(buffer.toString('utf8',20,20+jsonLength));assert.ok(gltf.nodes.some(n=>n.extras?.editorId===newIds[2]));assert.ok(!gltf.nodes.some(n=>n.extras?.editorId==='milk_fridge'));assert.ok(gltf.meshes.length>20);
  const png=page.waitForEvent('download');await page.locator('#export-menu summary').click();await page.locator('[data-export="png"]').click();await (await png).saveAs(path.join(output,'editor-test-export.png'));assert.equal(fs.readFileSync(path.join(output,'editor-test-export.png')).readUInt32BE(0),0x89504e47);
  passed.push('SVG is valid, area-grouped with robot reach packages; SVG scene import restores edits. GLB contains added robots and excludes hidden objects; PNG exports successfully.');
  await page.waitForFunction(()=>document.querySelector('#save-status').textContent.startsWith('Saved locally'));await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>coffeeEditor.ready);s=await state();assert.equal(s.scene.objects.length,32);assert.equal(s.models.find(([id])=>id==='milk_fridge')[1].visible,false);passed.push('Local autosave survives reload with added models and visibility intact.');
  // Leave pristine preview screenshots and no test edits in the browser profile.
  await page.evaluate(()=>{coffeeEditor.store.reset();coffeeEditor.store.setOption('showAllReach',false);coffeeEditor.store.setOption('showAllDistances',false);coffeeEditor.store.setOption('view','split');coffeeEditor.plan.fit();});
  await page.screenshot({path:path.join(output,'editor-overview.png')});
  await select('nova2');await page.locator('#scene-focus').click();await page.screenshot({path:path.join(output,'editor-coffee.png')});
  const finalScene=await state();const ice=finalScene.scene.objects.find(o=>o.id==='ice_machine'),n2=finalScene.scene.objects.find(o=>o.id==='nova2');assert.ok(ice.width<ice.depth&&ice.y>n2.y);assert.equal(ice.yaw_deg,0);
  assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'editor-test-report.json'),JSON.stringify({passed,errors,exports:{svg:svg.length,glb:buffer.length}},null,2));console.log(JSON.stringify({passed,errors,exports:{svg:svg.length,glb:buffer.length}},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
