const {chromium} = require('C:/Users/andyl/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('fs');
const path = require('path');
const assert = require('assert');

(async () => {
  const browser = await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe', headless:true, args:['--enable-unsafe-swiftshader']});
  try {
    const page = await browser.newPage({viewport:{width:1500,height:1000},acceptDownloads:true});
    const errors=[];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto('http://127.0.0.1:8766/viewer.html');
    await page.waitForFunction(() => document.getElementById('status').textContent.includes('editable objects loaded'), null, {timeout:60000});
    const initial = await page.evaluate(() => window.bakeryViewer.getConfig());
    const transform = id => page.evaluate(id => window.bakeryViewer.getTransform(id), id);
    const edit = async (id, value) => { await page.locator('#'+id).fill(String(value)); await page.locator('#'+id).press('Tab'); };
    const near = (a,b,why) => assert(Math.abs(a-b)<1e-5, `${why}: ${a} != ${b}`);
    for (const object of initial.objects) assert(await transform(object.id), 'Missing '+object.id);
    const iceBefore = await transform('ice_machine');
    const novaBefore = await transform('nova2');
    await page.locator('#objectSelect').selectOption('coffee_station');
    await edit('heightInput',1);
    near((await transform('ice_machine')).position[1]-iceBefore.position[1],.1,'machine follows support height');
    near((await transform('nova2')).position[1]-novaBefore.position[1],.1,'Nova-2 follows coffee table height');
    await page.locator('#objectSelect').selectOption('nova5');
    await edit('xInput',1.75);
    near((await transform('nova5_range')).position[0],1.75,'range follows robot');
    await page.locator('#equipmentToggle').uncheck();
    assert.equal((await transform('ice_machine')).visible,false);
    assert.equal((await transform('charger')).visible,true);
    await page.locator('#rangesToggle').uncheck();
    assert.equal((await transform('nova5_range')).visible,false);
    const downloading = page.waitForEvent('download');
    await page.locator('#downloadButton').click();
    const download = await downloading;
    const downloadedPath=path.join(__dirname,'output','viewer-roundtrip.json');
    await download.saveAs(downloadedPath);
    const saved=JSON.parse(fs.readFileSync(downloadedPath,'utf8'));
    assert.equal(saved.objects.find(o=>o.id==='coffee_station').height,1);
    assert.equal(saved.objects.find(o=>o.id==='nova5_range').x,1.75);
    const imported=structuredClone(initial);
    imported.objects.find(o=>o.id==='charger').x-=.1;
    await page.locator('#fileInput').setInputFiles({name:'scene_config.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});
    await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Imported'));
    near((await transform('charger')).position[0],2.744,'dock import position');
    assert.equal((await transform('ice_machine')).visible,true);
    await page.locator('#resetButton').click();
    near((await transform('charger')).position[0],2.844,'dock reset');
    near((await transform('ice_machine')).position[1],iceBefore.position[1],'support reset');
    await page.locator('#objectSelect').selectOption('human');
    await page.screenshot({path:path.join(__dirname,'output','viewer.png')});
    await page.locator('#topView').click();
    await page.screenshot({path:path.join(__dirname,'output','viewer-top.png')});
    await page.locator('#coffeeView').click();
    await page.screenshot({path:path.join(__dirname,'output','viewer-coffee.png')});
    await page.locator('#dockView').click();
    await page.screenshot({path:path.join(__dirname,'output','viewer-dock.png')});
    assert.deepStrictEqual(errors,[],'browser errors');
    const result={passed:true,editable_objects:initial.objects.length,checks:['GLB hierarchy load','machine support heights','range follows robot','equipment visibility','range visibility','JSON export/import','reset','dock camera'],page_errors:errors};
    fs.writeFileSync(path.join(__dirname,'output','viewer-verification.json'),JSON.stringify(result,null,2));
    console.log(JSON.stringify(result));
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exit(1)});
